name: my ascii workflow
on: push
env:
    ARTIFACTFILE: dragon.txt
jobs:
    build_job:
        runs-on: ubuntu-22.04
        steps:
            - name: pull the repo
              uses: actions/checkout@v7
            - name: step1
              run: |
                   chmod +x ./myscripts/script1.sh
                    ./myscripts/script1.sh
            - name: upload artifact
              uses: actions/upload-artifact@v7
              with: 
                name: shared
                path: ${{env.ARTIFACTFILE}}

                    
            
    test_job:
        runs-on: ubuntu-22.04
        needs: build_job
        steps:
            - name: download artifact
              uses: actions/download-artifact@v7
              with:
                name: shared
                path: .
            - name: test
              run: grep "dragon" ${{env.ARTIFACTFILE}}


    deploy_job:
        runs-on: ubuntu-22.04
        needs: test_job
        steps:
            - name: download artifact
              uses: actions/download-artifact@v7
              with: 
                name: shared
                path: .
            - name: deploy
              run: cat ${{env.ARTIFACTFILE}}