name: my ascii workflow
on: push
jobs:
    myjob1:
        runs-on: ubuntu-22.04
        steps:
            - name: pull the repo
              uses: actions/checkout@v7
            - name: step1
              run: ./myscripts/script1.sh