name: my first workflow
on: push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps: 
    - name: download the repo 
      uses: actions/checkout@v7
    - name: step one
      run: echo "step 1"
    - name: step 2
      run: ls
    - name: step 3
      run: cat README.md
    - name: multi line step
      run: |
           echo "hello"
           ls -alhrt
           cat README.md
    - name: use cowsay
      run: |
           apt install cowsay -y
           cowsay -f dragon