name: myotherworkflow
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-22.04
        steps:
            - name: echo password
              run: echo "this is my password ${{secrets.MYPASSWORD}}"
